package com.goldsilver.livecalc.util

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.unit.LayoutDirection

data class AppStrings(
    // App & Common
    val appName: String,
    val spot: String,
    val liveRates: String,
    val refresh: String,
    val cancel: String,
    val save: String,
    val delete: String,
    val done: String,
    val back: String,
    val retry: String,
    val error: String,
    val loading: String,
    val noInternet: String,
    val share: String,
    val perGram: String,

    // Navigation Tabs
    val tabRates: String,
    val tabTrends: String,
    val tabCalculator: String,
    val tabHallmark: String,
    val tabAlerts: String,
    val tabSettings: String,

    // Home / Dashboard
    val goldRates: String,
    val silverRates: String,
    val gold24k: String,
    val gold22k: String,
    val gold18k: String,
    val gold14k: String,
    val silverPure: String,
    val purity24kDesc: String,
    val purity22kDesc: String,
    val purity18kDesc: String,
    val purity14kDesc: String,
    val silver999Desc: String,
    val liveRateCardSubtitle: String,
    val quickCalculator: String,
    val calculatePrice: String,
    val hallmarkBannerTitle: String,
    val hallmarkBannerSubtitle: String,
    val verifyNow: String,
    val priceAlertsBannerTitle: String,
    val priceAlertsBannerSubtitle: String,
    val setAlert: String,
    val lastUpdated: String,

    // Historical Trends & Charts
    val historicalTrends: String,
    val range7D: String,
    val range30D: String,
    val range1Y: String,
    val high: String,
    val low: String,
    val currentRate: String,
    val marketSummary: String,
    val todaysChange: String,
    val highestRate: String,
    val lowestRate: String,
    val averagePrice: String,
    val initialRecord: String,
    val noHistoricalData: String,
    val premiumFeature: String,
    val unlockTrendsDesc: String,
    val upgradeToPremium: String,

    // Calculators (Gold & Silver)
    val goldCalculator: String,
    val silverCalculator: String,
    val weightInGrams: String,
    val enterWeight: String,
    val selectPurity: String,
    val makingCharges: String,
    val percentage: String,
    val fixedAmount: String,
    val gstTax: String,
    val priceBreakdown: String,
    val baseMetalPrice: String,
    val totalMakingCharges: String,
    val gstAmount: String,
    val totalPayable: String,
    val calculate: String,
    val reset: String,
    val pleaseEnterWeight: String,

    // Hallmark Verification
    val hallmarkTitle: String,
    val hallmarkSubtitle: String,
    val enterHuidCode: String,
    val huidPlaceholder: String,
    val verifyHuid: String,
    val verifying: String,
    val verifiedAuthentic: String,
    val unverifiedRecord: String,
    val huidNumber: String,
    val articleType: String,
    val metalPurity: String,
    val assayCenter: String,
    val verificationDate: String,
    val verifyAnother: String,
    val invalidHuidMessage: String,

    // Price Alerts
    val priceAlertsTitle: String,
    val priceAlertsSubtitle: String,
    val createAlert: String,
    val selectMetal: String,
    val metalGold: String,
    val metalSilver: String,
    val alertCondition: String,
    val risesAbove: String,
    val fallsBelow: String,
    val targetPrice: String,
    val enterTargetPrice: String,
    val activeAlerts: String,
    val noAlertsCreated: String,
    val alertCreatedSuccess: String,
    val pleaseEnterTargetPrice: String,

    // Settings
    val settingsTitle: String,
    val preferencesAndAlerts: String,
    val priceAlertNotifications: String,
    val alertsEnabledDesc: String,
    val alertsDisabledDesc: String,
    val displayCurrency: String,
    val appLanguage: String,
    val backgroundTheme: String,
    val themeNight: String,
    val themeMidnight: String,
    val themeCharcoal: String,
    val themeOnyx: String,
    val themeDeepBlue: String,
    val themeEmerald: String,
    val themeAmethyst: String,
    val themeBurgundy: String,
    val aboutAndSupport: String,
    val rateApp: String,
    val shareApp: String,
    val privacyPolicy: String,
    val termsOfService: String,
    val appVersion: String,
    val developer: String,

    // App Update Dialog
    val updateAvailable: String,
    val updateNow: String,
    val later: String,
    val newVersionReady: String
)

val EnglishStrings = AppStrings(
    appName = "Gold Silver Live Calc",
    spot = "Spot",
    liveRates = "Live Metal Rates",
    refresh = "Refresh",
    cancel = "Cancel",
    save = "Save",
    delete = "Delete",
    done = "Done",
    back = "Back",
    retry = "Retry",
    error = "Error",
    loading = "Loading...",
    noInternet = "No internet connection",
    share = "Share",
    perGram = "/g",

    tabRates = "Rates",
    tabTrends = "Trends",
    tabCalculator = "Calculator",
    tabHallmark = "Hallmark",
    tabAlerts = "Alerts",
    tabSettings = "Settings",

    goldRates = "Gold Rates",
    silverRates = "Silver Rates",
    gold24k = "Gold (24K)",
    gold22k = "Gold (22K)",
    gold18k = "Gold (18K)",
    gold14k = "Gold (14K)",
    silverPure = "Silver (99.9%)",
    purity24kDesc = "99.9% Pure • Fine Gold",
    purity22kDesc = "91.6% Pure • Jewelry Gold",
    purity18kDesc = "75.0% Pure • Standard Gold",
    purity14kDesc = "58.3% Pure • Commercial Gold",
    silver999Desc = "99.9% Pure • Fine Silver",
    liveRateCardSubtitle = "Live Spot Market Price",
    quickCalculator = "Quick Calculator",
    calculatePrice = "Calculate Price",
    hallmarkBannerTitle = "Hallmark (HUID) Verification",
    hallmarkBannerSubtitle = "Check authenticity with 6-digit BIS HUID code",
    verifyNow = "Verify Now",
    priceAlertsBannerTitle = "Smart Price Alerts",
    priceAlertsBannerSubtitle = "Get notified instantly when rates cross your target",
    setAlert = "Set Alert",
    lastUpdated = "Last updated",

    historicalTrends = "Historical Trends",
    range7D = "7D",
    range30D = "30D",
    range1Y = "1Y",
    high = "HIGH",
    low = "LOW",
    currentRate = "CURRENT RATE",
    marketSummary = "Market Summary",
    todaysChange = "Today's Change",
    highestRate = "Highest Rate",
    lowestRate = "Lowest Rate",
    averagePrice = "Average Price",
    initialRecord = "Initial Record",
    noHistoricalData = "No historical data available",
    premiumFeature = "1-Year Trends is a Premium Feature",
    unlockTrendsDesc = "Unlock long-term investment graphs and deeper market analytics.",
    upgradeToPremium = "Upgrade to Premium",

    goldCalculator = "Gold Calculator",
    silverCalculator = "Silver Calculator",
    weightInGrams = "Weight (Grams)",
    enterWeight = "Enter weight in grams",
    selectPurity = "Select Purity",
    makingCharges = "Making Charges",
    percentage = "Percentage (%)",
    fixedAmount = "Fixed (Per Gram)",
    gstTax = "GST / Tax",
    priceBreakdown = "Price Breakdown",
    baseMetalPrice = "Base Metal Price",
    totalMakingCharges = "Total Making Charges",
    gstAmount = "GST Amount",
    totalPayable = "Total Payable Amount",
    calculate = "Calculate",
    reset = "Reset",
    pleaseEnterWeight = "Please enter a valid weight",

    hallmarkTitle = "Hallmark Verification",
    hallmarkSubtitle = "Verify 6-digit alphanumeric BIS HUID unique code",
    enterHuidCode = "Enter 6-Digit HUID Code",
    huidPlaceholder = "e.g., AB12CD",
    verifyHuid = "Verify HUID",
    verifying = "Verifying...",
    verifiedAuthentic = "Verified Authentic Hallmark",
    unverifiedRecord = "Unverified / Not in Registry",
    huidNumber = "HUID Number",
    articleType = "Article Type",
    metalPurity = "Metal & Purity",
    assayCenter = "Assaying & Hallmarking Center",
    verificationDate = "Verification Date",
    verifyAnother = "Verify Another Code",
    invalidHuidMessage = "Please enter a valid 6-character alphanumeric code",

    priceAlertsTitle = "Price Alerts",
    priceAlertsSubtitle = "Set alerts and get notified when target prices are reached",
    createAlert = "Create Alert",
    selectMetal = "Select Metal",
    metalGold = "Gold",
    metalSilver = "Silver",
    alertCondition = "Condition",
    risesAbove = "Rises Above (≥)",
    fallsBelow = "Falls Below (≤)",
    targetPrice = "Target Price",
    enterTargetPrice = "Enter target price per gram",
    activeAlerts = "Active Alerts",
    noAlertsCreated = "No price alerts set yet. Tap + to create one.",
    alertCreatedSuccess = "Price alert created successfully!",
    pleaseEnterTargetPrice = "Please enter a valid target price",

    settingsTitle = "Settings",
    preferencesAndAlerts = "PREFERENCES & ALERTS",
    priceAlertNotifications = "Gold & Silver Price Alerts",
    alertsEnabledDesc = "Alerts enabled for target rates",
    alertsDisabledDesc = "Alerts disabled",
    displayCurrency = "Display Currency",
    appLanguage = "App Language",
    backgroundTheme = "Background Theme",
    themeNight = "Night (Default)",
    themeMidnight = "Midnight Blue",
    themeCharcoal = "Charcoal",
    themeOnyx = "Onyx Black",
    themeDeepBlue = "Deep Ocean",
    themeEmerald = "Emerald",
    themeAmethyst = "Amethyst",
    themeBurgundy = "Burgundy",
    aboutAndSupport = "ABOUT & SUPPORT",
    rateApp = "Rate Us on Play Store",
    shareApp = "Share App with Friends",
    privacyPolicy = "Privacy Policy",
    termsOfService = "Terms of Service",
    appVersion = "App Version",
    developer = "Developer",

    updateAvailable = "Update Available",
    updateNow = "Update Now",
    later = "Later",
    newVersionReady = "A new version is ready with the latest rates and improvements."
)

val HindiStrings = AppStrings(
    appName = "Gold Silver Live Calc",
    spot = "हाजिर भाव",
    liveRates = "सोना और चांदी लाइव भाव",
    refresh = "ताज़ा करें",
    cancel = "रद्द करें",
    save = "सहेजें",
    delete = "हटाएं",
    done = "पूर्ण",
    back = "पीछे",
    retry = "पुनः प्रयास करें",
    error = "त्रुटि",
    loading = "लोड हो रहा है...",
    noInternet = "कोई इंटरनेट कनेक्शन नहीं है",
    share = "साझा करें",
    perGram = "/ग्राम",

    tabRates = "भाव",
    tabTrends = "ट्रेंड्स",
    tabCalculator = "कैलकुलेटर",
    tabHallmark = "हॉलमार्क",
    tabAlerts = "अलर्ट",
    tabSettings = "सेटिंग्स",

    goldRates = "सोने का भाव",
    silverRates = "चांदी का भाव",
    gold24k = "सोना (24K)",
    gold22k = "सोना (22K)",
    gold18k = "सोना (18K)",
    gold14k = "सोना (14K)",
    silverPure = "चांदी (99.9%)",
    purity24kDesc = "99.9% शुद्ध • शुद्ध सोना",
    purity22kDesc = "91.6% शुद्ध • आभूषण सोना",
    purity18kDesc = "75.0% शुद्ध • मानक सोना",
    purity14kDesc = "58.3% शुद्ध • कमर्शियल सोना",
    silver999Desc = "99.9% शुद्ध • शुद्ध चांदी",
    liveRateCardSubtitle = "लाइव स्पॉट मार्केट रेट",
    quickCalculator = "त्वरित कैलकुलेटर",
    calculatePrice = "कीमत की गणना करें",
    hallmarkBannerTitle = "हॉलमार्क (HUID) सत्यापन",
    hallmarkBannerSubtitle = "6-अंकीय BIS HUID कोड से शुद्धता जांचें",
    verifyNow = "अभी जांचें",
    priceAlertsBannerTitle = "स्मार्ट प्राइस अलर्ट",
    priceAlertsBannerSubtitle = "लक्ष्य दर पार होने पर तुरंत सूचना प्राप्त करें",
    setAlert = "अलर्ट सेट करें",
    lastUpdated = "अंतिम अपडेट",

    historicalTrends = "ऐतिहासिक ट्रेंड्स",
    range7D = "7 दिन",
    range30D = "30 दिन",
    range1Y = "1 वर्ष",
    high = "उच्चतम",
    low = "न्यूनतम",
    currentRate = "वर्तमान दर",
    marketSummary = "बाजार सारांश",
    todaysChange = "आज का बदलाव",
    highestRate = "उच्चतम दर",
    lowestRate = "न्यूनतम दर",
    averagePrice = "औसत कीमत",
    initialRecord = "प्रारंभिक रिकॉर्ड",
    noHistoricalData = "कोई ऐतिहासिक डेटा उपलब्ध नहीं है",
    premiumFeature = "1 वर्ष का ट्रेंड प्रीमियम सुविधा है",
    unlockTrendsDesc = "दीर्घकालिक निवेश ग्राफ और गहन विश्लेषण अनलॉक करें।",
    upgradeToPremium = "प्रीमियम में अपग्रेड करें",

    goldCalculator = "गोल्ड कैलकुलेटर",
    silverCalculator = "सिल्वर कैलकुलेटर",
    weightInGrams = "वजन (ग्राम)",
    enterWeight = "ग्राम में वजन दर्ज करें",
    selectPurity = "शुद्धता चुनें",
    makingCharges = "मेकिंग चार्ज (घड़ाई)",
    percentage = "प्रतिशत (%)",
    fixedAmount = "निश्चित (प्रति ग्राम)",
    gstTax = "जीएसटी / टैक्स",
    priceBreakdown = "मूल्य विवरण",
    baseMetalPrice = "मूल धातु मूल्य",
    totalMakingCharges = "कुल मेकिंग चार्ज",
    gstAmount = "जीएसटी राशि",
    totalPayable = "कुल देय राशि",
    calculate = "गणना करें",
    reset = "रीसेट",
    pleaseEnterWeight = "कृपया एक मान्य वजन दर्ज करें",

    hallmarkTitle = "हॉलमार्क सत्यापन",
    hallmarkSubtitle = "6-अंकीय BIS HUID यूनिक कोड सत्यापित करें",
    enterHuidCode = "6-अंकीय HUID कोड दर्ज करें",
    huidPlaceholder = "उदा. AB12CD",
    verifyHuid = "HUID सत्यापित करें",
    verifying = "सत्यापन हो रहा है...",
    verifiedAuthentic = "सत्यापित प्रामाणिक हॉलमार्क",
    unverifiedRecord = "अपुष्ट / रिकॉर्ड में नहीं मिला",
    huidNumber = "HUID संख्या",
    articleType = "आभूषण का प्रकार",
    metalPurity = "धातु और शुद्धता",
    assayCenter = "परख एवं हॉलमार्किंग केंद्र",
    verificationDate = "सत्यापन तिथि",
    verifyAnother = "अन्य कोड सत्यापित करें",
    invalidHuidMessage = "कृपया 6-अक्षरों का मान्य कोड दर्ज करें",

    priceAlertsTitle = "प्राइस अलर्ट",
    priceAlertsSubtitle = "लक्ष्य मूल्य सेट करें और समय पर सूचना पाएं",
    createAlert = "अलर्ट बनाएं",
    selectMetal = "धातु चुनें",
    metalGold = "सोना",
    metalSilver = "चांदी",
    alertCondition = "शर्त",
    risesAbove = "इससे ऊपर जाने पर (≥)",
    fallsBelow = "इससे नीचे जाने पर (≤)",
    targetPrice = "लक्ष्य मूल्य",
    enterTargetPrice = "प्रति ग्राम लक्ष्य मूल्य दर्ज करें",
    activeAlerts = "सक्रिय अलर्ट",
    noAlertsCreated = "कोई अलर्ट सेट नहीं है। नया अलर्ट जोड़ने के लिए + दबाएं।",
    alertCreatedSuccess = "प्राइस अलर्ट सफलतापूर्वक बनाया गया!",
    pleaseEnterTargetPrice = "कृपया एक मान्य लक्ष्य मूल्य दर्ज करें",

    settingsTitle = "सेटिंग्स",
    preferencesAndAlerts = "प्राथमिकताएं और अलर्ट",
    priceAlertNotifications = "सोना और चांदी प्राइस अलर्ट",
    alertsEnabledDesc = "लक्ष्य दरों के लिए सूचनाएं चालू हैं",
    alertsDisabledDesc = "सूचनाएं बंद हैं",
    displayCurrency = "मुद्रा (करेंसी)",
    appLanguage = "ऐप की भाषा",
    backgroundTheme = "बैकग्राउंड थीम",
    themeNight = "नाइट (डिफ़ॉल्ट)",
    themeMidnight = "मिडनाइट ब्लू",
    themeCharcoal = "चारकोल",
    themeOnyx = "गोल्डन ब्लैक",
    themeDeepBlue = "डीप ओशन",
    themeEmerald = "पन्ना हरा",
    themeAmethyst = "नीलम बैंगनी",
    themeBurgundy = "बरगंडी",
    aboutAndSupport = "के बारे में और सहायता",
    rateApp = "प्ले स्टोर पर हमें रेटिंग दें",
    shareApp = "मित्रों के साथ ऐप साझा करें",
    privacyPolicy = "गोपनीयता नीति",
    termsOfService = "सेवा की शर्तें",
    appVersion = "ऐप संस्करण",
    developer = "डेवलपर",

    updateAvailable = "नया अपडेट उपलब्ध है",
    updateNow = "अभी अपडेट करें",
    later = "बाद में",
    newVersionReady = "ताजा दरों और सुधारों के साथ नया संस्करण उपलब्ध है।"
)

val SpanishStrings = AppStrings(
    appName = "Gold Silver Live Calc",
    spot = "Spot",
    liveRates = "Precios de Metales en Vivo",
    refresh = "Actualizar",
    cancel = "Cancelar",
    save = "Guardar",
    delete = "Eliminar",
    done = "Hecho",
    back = "Atrás",
    retry = "Reintentar",
    error = "Error",
    loading = "Cargando...",
    noInternet = "Sin conexión a internet",
    share = "Compartir",
    perGram = "/g",

    tabRates = "Precios",
    tabTrends = "Tendencias",
    tabCalculator = "Calculadora",
    tabHallmark = "Contraste",
    tabAlerts = "Alertas",
    tabSettings = "Ajustes",

    goldRates = "Precios del Oro",
    silverRates = "Precios de la Plata",
    gold24k = "Oro (24K)",
    gold22k = "Oro (22K)",
    gold18k = "Oro (18K)",
    gold14k = "Oro (14K)",
    silverPure = "Plata (99.9%)",
    purity24kDesc = "99.9% Puro • Oro Fino",
    purity22kDesc = "91.6% Puro • Joyería",
    purity18kDesc = "75.0% Puro • Estándar",
    purity14kDesc = "58.3% Puro • Comercial",
    silver999Desc = "99.9% Puro • Plata Fina",
    liveRateCardSubtitle = "Precio Spot del Mercado en Vivo",
    quickCalculator = "Calculadora Rápida",
    calculatePrice = "Calcular Precio",
    hallmarkBannerTitle = "Verificación de Contraste (HUID)",
    hallmarkBannerSubtitle = "Compruebe autenticidad con código alfanumérico",
    verifyNow = "Verificar Ahora",
    priceAlertsBannerTitle = "Alertas de Precio Inteligentes",
    priceAlertsBannerSubtitle = "Reciba notificaciones cuando se alcance su objetivo",
    setAlert = "Crear Alerta",
    lastUpdated = "Última actualización",

    historicalTrends = "Tendencias Históricas",
    range7D = "7D",
    range30D = "30D",
    range1Y = "1A",
    high = "MÁXIMO",
    low = "MÍNIMO",
    currentRate = "PRECIO ACTUAL",
    marketSummary = "Resumen del Mercado",
    todaysChange = "Cambio de Hoy",
    highestRate = "Precio Más Alto",
    lowestRate = "Precio Más Bajo",
    averagePrice = "Precio Promedio",
    initialRecord = "Registro Inicial",
    noHistoricalData = "No hay datos históricos disponibles",
    premiumFeature = "Tendencias de 1 año es una función Premium",
    unlockTrendsDesc = "Desbloquee gráficos a largo plazo y análisis más profundos.",
    upgradeToPremium = "Mejorar a Premium",

    goldCalculator = "Calculadora de Oro",
    silverCalculator = "Calculadora de Plata",
    weightInGrams = "Peso (Gramos)",
    enterWeight = "Ingrese el peso en gramos",
    selectPurity = "Seleccionar Pureza",
    makingCharges = "Mano de Obra",
    percentage = "Porcentaje (%)",
    fixedAmount = "Fijo (Por Gramo)",
    gstTax = "Impuestos / IVA",
    priceBreakdown = "Desglose del Precio",
    baseMetalPrice = "Precio Base del Metal",
    totalMakingCharges = "Total Mano de Obra",
    gstAmount = "Monto de Impuestos",
    totalPayable = "Monto Total a Pagar",
    calculate = "Calcular",
    reset = "Restablecer",
    pleaseEnterWeight = "Por favor ingrese un peso válido",

    hallmarkTitle = "Verificación de Contraste",
    hallmarkSubtitle = "Verifique el código único alfanumérico de 6 dígitos",
    enterHuidCode = "Ingrese el Código HUID de 6 Dígitos",
    huidPlaceholder = "ej. AB12CD",
    verifyHuid = "Verificar HUID",
    verifying = "Verificando...",
    verifiedAuthentic = "Contraste Auténtico Verificado",
    unverifiedRecord = "No Verificado / No Encontrado",
    huidNumber = "Número HUID",
    articleType = "Tipo de Artículo",
    metalPurity = "Metal y Pureza",
    assayCenter = "Centro de Ensaye y Contraste",
    verificationDate = "Fecha de Verificación",
    verifyAnother = "Verificar Otro Código",
    invalidHuidMessage = "Ingrese un código alfanumérico válido de 6 caracteres",

    priceAlertsTitle = "Alertas de Precio",
    priceAlertsSubtitle = "Establezca alertas cuando los precios alcancen su objetivo",
    createAlert = "Crear Alerta",
    selectMetal = "Seleccionar Metal",
    metalGold = "Oro",
    metalSilver = "Plata",
    alertCondition = "Condición",
    risesAbove = "Sube por encima de (≥)",
    fallsBelow = "Cae por debajo de (≤)",
    targetPrice = "Precio Objetivo",
    enterTargetPrice = "Ingrese el precio objetivo por gramo",
    activeAlerts = "Alertas Activas",
    noAlertsCreated = "No hay alertas creadas. Toque + para crear una.",
    alertCreatedSuccess = "¡Alerta creada con éxito!",
    pleaseEnterTargetPrice = "Por favor ingrese un precio objetivo válido",

    settingsTitle = "Ajustes",
    preferencesAndAlerts = "PREFERENCIAS Y ALERTAS",
    priceAlertNotifications = "Alertas de Precio de Oro y Plata",
    alertsEnabledDesc = "Alertas activadas para precios objetivo",
    alertsDisabledDesc = "Alertas desactivadas",
    displayCurrency = "Moneda",
    appLanguage = "Idioma de la Aplicación",
    backgroundTheme = "Tema de Fondo",
    themeNight = "Noche (Predeterminado)",
    themeMidnight = "Azul Medianoche",
    themeCharcoal = "Carbón",
    themeOnyx = "Negro Ónix",
    themeDeepBlue = "Océano Profundo",
    themeEmerald = "Esmeralda",
    themeAmethyst = "Amatista",
    themeBurgundy = "Borgoña",
    aboutAndSupport = "ACERCA DE Y SOPORTE",
    rateApp = "Califícanos en Play Store",
    shareApp = "Compartir con Amigos",
    privacyPolicy = "Política de Privacidad",
    termsOfService = "Términos de Servicio",
    appVersion = "Versión de la App",
    developer = "Desarrollador",

    updateAvailable = "Actualización Disponible",
    updateNow = "Actualizar Ahora",
    later = "Más Tarde",
    newVersionReady = "Una nueva versión está lista con mejoras y cotizaciones en vivo."
)

val ArabicStrings = AppStrings(
    appName = "Gold Silver Live Calc",
    spot = "فوري",
    liveRates = "أسعار المعادن المباشرة",
    refresh = "تحديث",
    cancel = "إلغاء",
    save = "حفظ",
    delete = "حذف",
    done = "تم",
    back = "رجوع",
    retry = "إعادة المحاولة",
    error = "خطأ",
    loading = "جارٍ التحميل...",
    noInternet = "لا يوجد اتصال بالإنترنت",
    share = "مشاركة",
    perGram = "/جرام",

    tabRates = "الأسعار",
    tabTrends = "المؤشرات",
    tabCalculator = "الحاسبة",
    tabHallmark = "الدمغة",
    tabAlerts = "التنبيهات",
    tabSettings = "الإعدادات",

    goldRates = "أسعار الذهب",
    silverRates = "أسعار الفضة",
    gold24k = "ذهب (24 قيراط)",
    gold22k = "ذهب (22 قيراط)",
    gold18k = "ذهب (18 قيراط)",
    gold14k = "ذهب (14 قيراط)",
    silverPure = "فضة نقية (99.9%)",
    purity24kDesc = "نقاء 99.9% • ذهب خالص",
    purity22kDesc = "نقاء 91.6% • ذهب مجوهرات",
    purity18kDesc = "نقاء 75.0% • ذهب قياسي",
    purity14kDesc = "نقاء 58.3% • ذهب تجاري",
    silver999Desc = "نقاء 99.9% • فضة خالصة",
    liveRateCardSubtitle = "سعر السوق الفوري المباشر",
    quickCalculator = "الحاسبة السريعة",
    calculatePrice = "حساب السعر",
    hallmarkBannerTitle = "التحقق من الدمغة (HUID)",
    hallmarkBannerSubtitle = "تحقق من الأصالة برمز HUID المكون من 6 خانات",
    verifyNow = "تحقق الآن",
    priceAlertsBannerTitle = "تنبيهات الأسعار الذكية",
    priceAlertsBannerSubtitle = "تلقي إشعارات فورية عند وصول الأسعار للهدف",
    setAlert = "ضبط التنبيه",
    lastUpdated = "آخر تحديث",

    historicalTrends = "المؤشرات التاريخية",
    range7D = "7 أيام",
    range30D = "30 يوم",
    range1Y = "سنة",
    high = "الأعلى",
    low = "الأدنى",
    currentRate = "السعر الحالي",
    marketSummary = "ملخص السوق",
    todaysChange = "تغير اليوم",
    highestRate = "أعلى سعر",
    lowestRate = "أدنى سعر",
    averagePrice = "متوسط السعر",
    initialRecord = "السجل الأولي",
    noHistoricalData = "لا توجد بيانات تاريخية متاحة",
    premiumFeature = "بيانات السنة ميزة مميزة (Premium)",
    unlockTrendsDesc = "افتح الرسوم البيانية الاستثمارية والتحليلات المتعمقة.",
    upgradeToPremium = "الترقية إلى Premium",

    goldCalculator = "حاسبة الذهب",
    silverCalculator = "حاسبة الفضة",
    weightInGrams = "الوزن (بالجرام)",
    enterWeight = "أدخل الوزن بالجرام",
    selectPurity = "اختر العيار والدرجة",
    makingCharges = "أجور المصنعية",
    percentage = "نسبة مئوية (%)",
    fixedAmount = "مبلغ ثابت (لكل جرام)",
    gstTax = "الضريبة / القيمة المضافة",
    priceBreakdown = "تفاصيل السعر",
    baseMetalPrice = "سعر المعدن الأساسي",
    totalMakingCharges = "إجمالي المصنعية",
    gstAmount = "مبلغ الضريبة",
    totalPayable = "المبلغ الإجمالي المستحق",
    calculate = "حساب",
    reset = "إعادة ضبط",
    pleaseEnterWeight = "يرجى إدخال وزن صحيح",

    hallmarkTitle = "التحقق من الدمغة الرسمية",
    hallmarkSubtitle = "التحقق من رمز HUID المكون من 6 أرقام وحروف",
    enterHuidCode = "أدخل رمز HUID",
    huidPlaceholder = "مثال: AB12CD",
    verifyHuid = "تحقق من الرمز",
    verifying = "جارٍ التحقق...",
    verifiedAuthentic = "دمغة أصلية معتمدة",
    unverifiedRecord = "غير موثق / غير موجود بالسجل",
    huidNumber = "رقم HUID",
    articleType = "نوع القطعة",
    metalPurity = "المعدن والعيار",
    assayCenter = "مركز الفحص والدمغ",
    verificationDate = "تاريخ التحقق",
    verifyAnother = "التحقق من رمز آخر",
    invalidHuidMessage = "يرجى إدخال رمز صحيح من 6 خانات",

    priceAlertsTitle = "تنبيهات الأسعار",
    priceAlertsSubtitle = "اضبط التنبيهات للحصول على إشعارات بالأسعار المطلوبة",
    createAlert = "إنشاء تنبيه",
    selectMetal = "اختر المعدن",
    metalGold = "ذهب",
    metalSilver = "فضة",
    alertCondition = "الشرط",
    risesAbove = "يرتفع عن (≥)",
    fallsBelow = "ينخفض عن (≤)",
    targetPrice = "السعر المستهدف",
    enterTargetPrice = "أدخل السعر المستهدف لكل جرام",
    activeAlerts = "التنبيهات النشطة",
    noAlertsCreated = "لا توجد تنبيهات حالياً. اضغط على + للإنشاء.",
    alertCreatedSuccess = "تم إنشاء التنبيه بنجاح!",
    pleaseEnterTargetPrice = "يرجى إدخال سعر مستهدف صحيح",

    settingsTitle = "الإعدادات",
    preferencesAndAlerts = "التفضيلات والتنبيهات",
    priceAlertNotifications = "إشعارات تنبيهات الأسعار",
    alertsEnabledDesc = "التنبيهات مفعلة للأسعار المستهدفة",
    alertsDisabledDesc = "التنبيهات معطلة",
    displayCurrency = "عملة العرض",
    appLanguage = "لغة التطبيق",
    backgroundTheme = "مظهر الخلفية",
    themeNight = "ليلي (الافتراضي)",
    themeMidnight = "أزرق منتصف الليل",
    themeCharcoal = "فحمي",
    themeOnyx = "أسود أونيكس",
    themeDeepBlue = "أزرق محيطي",
    themeEmerald = "زمردي",
    themeAmethyst = "أرجواني",
    themeBurgundy = "عنابي",
    aboutAndSupport = "حول التطبيق والدعم",
    rateApp = "تقييم التطبيق على المتجر",
    shareApp = "مشاركة التطبيق مع الأصدقاء",
    privacyPolicy = "سياسة الخصوصية",
    termsOfService = "شروط الخدمة",
    appVersion = "إصدار التطبيق",
    developer = "المطور",

    updateAvailable = "يتوفر تحديث جديد",
    updateNow = "تحديث الآن",
    later = "لاحقاً",
    newVersionReady = "إصدار جديد متوفر مع أحدث الأسعار والتحسينات."
)

val FrenchStrings = AppStrings(
    appName = "Gold Silver Live Calc",
    spot = "Spot",
    liveRates = "Cours des Métaux en Direct",
    refresh = "Actualiser",
    cancel = "Annuler",
    save = "Enregistrer",
    delete = "Supprimer",
    done = "Terminé",
    back = "Retour",
    retry = "Réessayer",
    error = "Erreur",
    loading = "Chargement...",
    noInternet = "Pas de connexion Internet",
    share = "Partager",
    perGram = "/g",

    tabRates = "Cours",
    tabTrends = "Tendances",
    tabCalculator = "Calculateur",
    tabHallmark = "Poinçon",
    tabAlerts = "Alertes",
    tabSettings = "Paramètres",

    goldRates = "Cours de l'Or",
    silverRates = "Cours de l'Argent",
    gold24k = "Or (24K)",
    gold22k = "Or (22K)",
    gold18k = "Or (18K)",
    gold14k = "Or (14K)",
    silverPure = "Argent (99.9%)",
    purity24kDesc = "99.9% Pur • Or Fin",
    purity22kDesc = "91.6% Pur • Bijouterie",
    purity18kDesc = "75.0% Pur • Standard",
    purity14kDesc = "58.3% Pur • Commercial",
    silver999Desc = "99.9% Pur • Argent Fin",
    liveRateCardSubtitle = "Prix Spot du Marché en Direct",
    quickCalculator = "Calculateur Rapide",
    calculatePrice = "Calculer le Prix",
    hallmarkBannerTitle = "Vérification de Poinçon (HUID)",
    hallmarkBannerSubtitle = "Vérifiez l'authenticité avec le code à 6 chiffres",
    verifyNow = "Vérifier",
    priceAlertsBannerTitle = "Alertes de Prix Intelligentes",
    priceAlertsBannerSubtitle = "Soyez notifié dès que vos objectifs de cours sont atteints",
    setAlert = "Créer Alerte",
    lastUpdated = "Dernière mise à jour",

    historicalTrends = "Tendances Historiques",
    range7D = "7J",
    range30D = "30J",
    range1Y = "1An",
    high = "HAUT",
    low = "BAS",
    currentRate = "COURS ACTUEL",
    marketSummary = "Résumé du Marché",
    todaysChange = "Variation du Jour",
    highestRate = "Plus Haut Cours",
    lowestRate = "Plus Bas Cours",
    averagePrice = "Prix Moyen",
    initialRecord = "Enregistrement Initial",
    noHistoricalData = "Aucune donnée historique disponible",
    premiumFeature = "Tendances 1 An est une fonction Premium",
    unlockTrendsDesc = "Débloquez les graphiques d'investissement et analyses approfondies.",
    upgradeToPremium = "Passer à Premium",

    goldCalculator = "Calculateur d'Or",
    silverCalculator = "Calculateur d'Argent",
    weightInGrams = "Poids (Grammes)",
    enterWeight = "Entrez le poids en grammes",
    selectPurity = "Sélectionnez la Pureté",
    makingCharges = "Frais de Fabrication / Façon",
    percentage = "Pourcentage (%)",
    fixedAmount = "Fixe (Par Gramme)",
    gstTax = "TVA / Taxes",
    priceBreakdown = "Détail du Prix",
    baseMetalPrice = "Prix du Métal de Base",
    totalMakingCharges = "Total Frais de Façon",
    gstAmount = "Montant de la Taxe",
    totalPayable = "Montant Total à Payer",
    calculate = "Calculer",
    reset = "Réinitialiser",
    pleaseEnterWeight = "Veuillez entrer un poids valide",

    hallmarkTitle = "Vérification de Poinçon",
    hallmarkSubtitle = "Vérifiez le code unique alphanumérique à 6 caractères",
    enterHuidCode = "Entrez le Code HUID",
    huidPlaceholder = "ex. AB12CD",
    verifyHuid = "Vérifier HUID",
    verifying = "Vérification...",
    verifiedAuthentic = "Poinçon Authentique Vérifié",
    unverifiedRecord = "Non vérifié / Introuvable",
    huidNumber = "Numéro HUID",
    articleType = "Type d'Article",
    metalPurity = "Métal et Titre",
    assayCenter = "Bureau de Garantie / Contrôle",
    verificationDate = "Date de Vérification",
    verifyAnother = "Vérifier un Autre Code",
    invalidHuidMessage = "Veuillez saisir un code alphanumérique valide de 6 caractères",

    priceAlertsTitle = "Alertes de Prix",
    priceAlertsSubtitle = "Définissez des alertes pour être notifié au bon moment",
    createAlert = "Créer une Alerte",
    selectMetal = "Sélectionnez le Métal",
    metalGold = "Or",
    metalSilver = "Argent",
    alertCondition = "Condition",
    risesAbove = "Dépasse (≥)",
    fallsBelow = "Passe sous (≤)",
    targetPrice = "Prix Cible",
    enterTargetPrice = "Entrez le prix cible par gramme",
    activeAlerts = "Alertes Actives",
    noAlertsCreated = "Aucune alerte définie. Touchez + pour en créer une.",
    alertCreatedSuccess = "Alerte de prix créée avec succès !",
    pleaseEnterTargetPrice = "Veuillez entrer un prix cible valide",

    settingsTitle = "Paramètres",
    preferencesAndAlerts = "PRÉFÉRENCES ET ALERTES",
    priceAlertNotifications = "Alertes Prix Or & Argent",
    alertsEnabledDesc = "Alertes activées pour les cours cibles",
    alertsDisabledDesc = "Alertes désactivées",
    displayCurrency = "Devise",
    appLanguage = "Langue de l'Application",
    backgroundTheme = "Thème de Fond",
    themeNight = "Nuit (Par Défaut)",
    themeMidnight = "Bleu Nuit",
    themeCharcoal = "Anthracite",
    themeOnyx = "Noir Onyx",
    themeDeepBlue = "Océan Profond",
    themeEmerald = "Émeraude",
    themeAmethyst = "Améthyste",
    themeBurgundy = "Bordeaux",
    aboutAndSupport = "À PROPOS ET SUPPORT",
    rateApp = "Noter l'App sur Play Store",
    shareApp = "Partager avec des Amis",
    privacyPolicy = "Politique de Confidentialité",
    termsOfService = "Conditions d'Utilisation",
    appVersion = "Version de l'App",
    developer = "Développeur",

    updateAvailable = "Mise à Jour Disponible",
    updateNow = "Mettre à Jour",
    later = "Plus Tard",
    newVersionReady = "Une nouvelle version est disponible avec les cours à jour et améliorations."
)

val PortugueseStrings = AppStrings(
    appName = "Gold Silver Live Calc",
    spot = "Spot",
    liveRates = "Cotações de Metais ao Vivo",
    refresh = "Atualizar",
    cancel = "Cancelar",
    save = "Salvar",
    delete = "Excluir",
    done = "Concluído",
    back = "Voltar",
    retry = "Tentar Novamente",
    error = "Erro",
    loading = "Carregando...",
    noInternet = "Sem conexão com a internet",
    share = "Compartilhar",
    perGram = "/g",

    tabRates = "Cotações",
    tabTrends = "Tendências",
    tabCalculator = "Calculadora",
    tabHallmark = "Contraste",
    tabAlerts = "Alertas",
    tabSettings = "Configurações",

    goldRates = "Cotação do Ouro",
    silverRates = "Cotação da Prata",
    gold24k = "Ouro (24K)",
    gold22k = "Ouro (22K)",
    gold18k = "Ouro (18K)",
    gold14k = "Ouro (14K)",
    silverPure = "Prata (99.9%)",
    purity24kDesc = "99.9% Puro • Ouro Fino",
    purity22kDesc = "91.6% Puro • Joalheria",
    purity18kDesc = "75.0% Puro • Padrão",
    purity14kDesc = "58.3% Puro • Comercial",
    silver999Desc = "99.9% Puro • Prata Fina",
    liveRateCardSubtitle = "Preço Spot de Mercado em Tempo Real",
    quickCalculator = "Calculadora Rápida",
    calculatePrice = "Calcular Preço",
    hallmarkBannerTitle = "Verificação de Contraste (HUID)",
    hallmarkBannerSubtitle = "Confira a autenticidade com o código de 6 dígitos",
    verifyNow = "Verificar Agora",
    priceAlertsBannerTitle = "Alertas de Preço Inteligentes",
    priceAlertsBannerSubtitle = "Seja notificado quando as cotações atingirem sua meta",
    setAlert = "Criar Alerta",
    lastUpdated = "Última atualização",

    historicalTrends = "Tendências Históricas",
    range7D = "7D",
    range30D = "30D",
    range1Y = "1A",
    high = "MÁXIMO",
    low = "MÍNIMO",
    currentRate = "COTAÇÃO ATUAL",
    marketSummary = "Resumo do Mercado",
    todaysChange = "Variação de Hoje",
    highestRate = "Maior Cotação",
    lowestRate = "Menor Cotação",
    averagePrice = "Preço Médio",
    initialRecord = "Registro Inicial",
    noHistoricalData = "Nenhum dado histórico disponível",
    premiumFeature = "Tendências de 1 ano é um recurso Premium",
    unlockTrendsDesc = "Desbloqueie gráficos de longo prazo e análises profundas.",
    upgradeToPremium = "Assinar Premium",

    goldCalculator = "Calculadora de Ouro",
    silverCalculator = "Calculadora de Prata",
    weightInGrams = "Peso (Gramas)",
    enterWeight = "Insira o peso em gramas",
    selectPurity = "Selecione a Pureza",
    makingCharges = "Taxa de Manufatura / Feitio",
    percentage = "Porcentagem (%)",
    fixedAmount = "Fixo (Por Grama)",
    gstTax = "Impostos / Tributos",
    priceBreakdown = "Detalhamento do Preço",
    baseMetalPrice = "Preço Base do Metal",
    totalMakingCharges = "Total da Manufatura",
    gstAmount = "Valor dos Impostos",
    totalPayable = "Valor Total a Pagar",
    calculate = "Calcular",
    reset = "Redefinir",
    pleaseEnterWeight = "Insira um peso válido",

    hallmarkTitle = "Verificação de Contraste",
    hallmarkSubtitle = "Verifique o código alfanumérico único de 6 dígitos",
    enterHuidCode = "Digite o Código HUID",
    huidPlaceholder = "ex. AB12CD",
    verifyHuid = "Verificar HUID",
    verifying = "Verificando...",
    verifiedAuthentic = "Contraste Autêntico Verificado",
    unverifiedRecord = "Não Verificado / Não Encontrado",
    huidNumber = "Número HUID",
    articleType = "Tipo de Artigo",
    metalPurity = "Metal e Pureza",
    assayCenter = "Centro de Ensaios e Contraste",
    verificationDate = "Data da Verificação",
    verifyAnother = "Verificar Outro Código",
    invalidHuidMessage = "Digite um código alfanumérico válido de 6 caracteres",

    priceAlertsTitle = "Alertas de Preço",
    priceAlertsSubtitle = "Defina alertas para receber notificações no momento certo",
    createAlert = "Criar Alerta",
    selectMetal = "Selecione o Metal",
    metalGold = "Ouro",
    metalSilver = "Prata",
    alertCondition = "Condição",
    risesAbove = "Subir acima de (≥)",
    fallsBelow = "Cair abaixo de (≤)",
    targetPrice = "Preço Alvo",
    enterTargetPrice = "Insira o preço alvo por grama",
    activeAlerts = "Alertas Ativos",
    noAlertsCreated = "Nenhum alerta criado. Toque em + para adicionar.",
    alertCreatedSuccess = "Alerta de preço criado com sucesso!",
    pleaseEnterTargetPrice = "Insira um preço alvo válido",

    settingsTitle = "Configurações",
    preferencesAndAlerts = "PREFERÊNCIAS E ALERTAS",
    priceAlertNotifications = "Notificações de Alerta de Preço",
    alertsEnabledDesc = "Alertas ativados para preços alvo",
    alertsDisabledDesc = "Alertas desativados",
    displayCurrency = "Moeda de Exibição",
    appLanguage = "Idioma do Aplicativo",
    backgroundTheme = "Tema de Fundo",
    themeNight = "Noite (Padrão)",
    themeMidnight = "Azul Meia-Noite",
    themeCharcoal = "Carvão",
    themeOnyx = "Preto Ônix",
    themeDeepBlue = "Oceano Profundo",
    themeEmerald = "Esmeralda",
    themeAmethyst = "Ametista",
    themeBurgundy = "Borgonha",
    aboutAndSupport = "SOBRE E SUPORTE",
    rateApp = "Avalie na Play Store",
    shareApp = "Compartilhar com Amigos",
    privacyPolicy = "Política de Privacidade",
    termsOfService = "Termos de Serviço",
    appVersion = "Versão do App",
    developer = "Desenvolvedor",

    updateAvailable = "Atualização Disponível",
    updateNow = "Atualizar Agora",
    later = "Mais Tarde",
    newVersionReady = "Uma nova versão está pronta com as últimas cotações e melhorias."
)

val IndonesianStrings = AppStrings(
    appName = "Gold Silver Live Calc",
    spot = "Spot",
    liveRates = "Harga Logam Mulia Live",
    refresh = "Segarkan",
    cancel = "Batal",
    save = "Simpan",
    delete = "Hapus",
    done = "Selesai",
    back = "Kembali",
    retry = "Coba Lagi",
    error = "Kesalahan",
    loading = "Memuat...",
    noInternet = "Tidak ada koneksi internet",
    share = "Bagikan",
    perGram = "/gram",

    tabRates = "Harga",
    tabTrends = "Tren",
    tabCalculator = "Kalkulator",
    tabHallmark = "Kadar",
    tabAlerts = "Peringatan",
    tabSettings = "Pengaturan",

    goldRates = "Harga Emas",
    silverRates = "Harga Perak",
    gold24k = "Emas (24K)",
    gold22k = "Emas (22K)",
    gold18k = "Emas (18K)",
    gold14k = "Emas (14K)",
    silverPure = "Perak Murni (99.9%)",
    purity24kDesc = "99.9% Murni • Emas Murni",
    purity22kDesc = "91.6% Murni • Emas Perhiasan",
    purity18kDesc = "75.0% Murni • Emas Standar",
    purity14kDesc = "58.3% Murni • Emas Komersial",
    silver999Desc = "99.9% Murni • Perak Murni",
    liveRateCardSubtitle = "Harga Pasar Spot Terkini",
    quickCalculator = "Kalkulator Cepat",
    calculatePrice = "Hitung Harga",
    hallmarkBannerTitle = "Verifikasi Keaslian (HUID)",
    hallmarkBannerSubtitle = "Periksa keaslian dengan kode alfanumerik 6 digit",
    verifyNow = "Verifikasi Sekarang",
    priceAlertsBannerTitle = "Peringatan Harga Pintar",
    priceAlertsBannerSubtitle = "Dapatkan notifikasi instan saat harga mencapai target",
    setAlert = "Pasang Peringatan",
    lastUpdated = "Terakhir diperbarui",

    historicalTrends = "Tren Historis",
    range7D = "7H",
    range30D = "30H",
    range1Y = "1T",
    high = "TERTINGGI",
    low = "TERENDAH",
    currentRate = "HARGA SAAT INI",
    marketSummary = "Ringkasan Pasar",
    todaysChange = "Perubahan Hari Ini",
    highestRate = "Harga Tertinggi",
    lowestRate = "Harga Terendah",
    averagePrice = "Harga Rata-rata",
    initialRecord = "Catatan Awal",
    noHistoricalData = "Data historis tidak tersedia",
    premiumFeature = "Tren 1 Tahun adalah Fitur Premium",
    unlockTrendsDesc = "Buka grafik investasi jangka panjang dan analitik mendalam.",
    upgradeToPremium = "Tingkatkan ke Premium",

    goldCalculator = "Kalkulator Emas",
    silverCalculator = "Kalkulator Perak",
    weightInGrams = "Berat (Gram)",
    enterWeight = "Masukkan berat dalam gram",
    selectPurity = "Pilih Kadar Kemurnian",
    makingCharges = "Ongkos Pembuatan",
    percentage = "Persentase (%)",
    fixedAmount = "Tetap (Per Gram)",
    gstTax = "PPN / Pajak",
    priceBreakdown = "Rincian Harga",
    baseMetalPrice = "Harga Dasar Logam",
    totalMakingCharges = "Total Ongkos Pembuatan",
    gstAmount = "Jumlah Pajak",
    totalPayable = "Total yang Harus Dibayar",
    calculate = "Hitung",
    reset = "Atur Ulang",
    pleaseEnterWeight = "Harap masukkan berat yang valid",

    hallmarkTitle = "Verifikasi Cap Kemurnian",
    hallmarkSubtitle = "Verifikasi kode unik HUID 6 digit alfanumerik",
    enterHuidCode = "Masukkan Kode HUID 6 Digit",
    huidPlaceholder = "cth. AB12CD",
    verifyHuid = "Verifikasi HUID",
    verifying = "Memverifikasi...",
    verifiedAuthentic = "Cap Kemurnian Asli Terverifikasi",
    unverifiedRecord = "Belum Terverifikasi / Tidak Ditemukan",
    huidNumber = "Nomor HUID",
    articleType = "Jenis Perhiasan",
    metalPurity = "Logam & Kemurnian",
    assayCenter = "Pusat Uji dan Cap Kemurnian",
    verificationDate = "Tanggal Verifikasi",
    verifyAnother = "Verifikasi Kode Lain",
    invalidHuidMessage = "Masukkan 6 karakter alfanumerik yang valid",

    priceAlertsTitle = "Peringatan Harga",
    priceAlertsSubtitle = "Atur target harga dan dapatkan notifikasi tepat waktu",
    createAlert = "Buat Peringatan",
    selectMetal = "Pilih Logam",
    metalGold = "Emas",
    metalSilver = "Perak",
    alertCondition = "Kondisi",
    risesAbove = "Naik di atas (≥)",
    fallsBelow = "Turun di bawah (≤)",
    targetPrice = "Harga Target",
    enterTargetPrice = "Masukkan harga target per gram",
    activeAlerts = "Peringatan Aktif",
    noAlertsCreated = "Belum ada peringatan harga. Ketuk + untuk membuat.",
    alertCreatedSuccess = "Peringatan harga berhasil dibuat!",
    pleaseEnterTargetPrice = "Harap masukkan harga target yang valid",

    settingsTitle = "Pengaturan",
    preferencesAndAlerts = "PREFERENSI & PERINGATAN",
    priceAlertNotifications = "Peringatan Harga Emas & Perak",
    alertsEnabledDesc = "Peringatan aktif untuk harga target",
    alertsDisabledDesc = "Peringatan dinonaktifkan",
    displayCurrency = "Mata Uang Tampilan",
    appLanguage = "Bahasa Aplikasi",
    backgroundTheme = "Tema Latar Belakang",
    themeNight = "Malam (Default)",
    themeMidnight = "Biru Tengah Malam",
    themeCharcoal = "Arang",
    themeOnyx = "Hitam Oniks",
    themeDeepBlue = "Samudra Dalam",
    themeEmerald = "Zamrud",
    themeAmethyst = "Kecubung",
    themeBurgundy = "Burgundi",
    aboutAndSupport = "TENTANG & DUKUNGAN",
    rateApp = "Beri Nilai di Play Store",
    shareApp = "Bagikan Aplikasi",
    privacyPolicy = "Kebijakan Privasi",
    termsOfService = "Ketentuan Layanan",
    appVersion = "Versi Aplikasi",
    developer = "Pengembang",

    updateAvailable = "Pembaruan Tersedia",
    updateNow = "Perbarui Sekarang",
    later = "Nanti",
    newVersionReady = "Versi baru telah siap dengan harga terkini dan peningkatan sistem."
)

fun getAppStrings(language: String): AppStrings {
    return when (language.lowercase()) {
        "hindi", "hi" -> HindiStrings
        "spanish", "es" -> SpanishStrings
        "arabic", "ar" -> ArabicStrings
        "french", "fr" -> FrenchStrings
        "portuguese", "pt" -> PortugueseStrings
        "indonesian", "id", "in" -> IndonesianStrings
        else -> EnglishStrings
    }
}

fun isRtlLanguage(language: String): Boolean {
    return language.equals("arabic", ignoreCase = true) || language.equals("ar", ignoreCase = true)
}

fun getSupportedLanguages(): List<Pair<String, String>> {
    return listOf(
        "English" to "English",
        "Hindi" to "हिन्दी",
        "Spanish" to "Español",
        "Arabic" to "العربية",
        "French" to "Français",
        "Portuguese" to "Português",
        "Indonesian" to "Bahasa Indonesia"
    )
}

val LocalAppStrings = compositionLocalOf { EnglishStrings }
